/**
 * education.ts — auto-generated from portfolio.json
 *
 * ✏️  To edit your education, open: src/config/portfolio.json → "education"
 *    Do NOT edit this file directly.
 */

import type { Education } from "@/features/portfolio/types/education"
import { education } from "@/lib/portfolio-config"

export const EDUCATION: Education[] = education || []
