/**
 * experiences.tsx — auto-generated from portfolio.json
 *
 * ✏️  To edit your experiences, open: src/config/portfolio.json → "experiences"
 *    Do NOT edit this file directly.
 */

import React from "react"
import {
  BriefcaseBusinessIcon,
  CodeXmlIcon,
  DraftingCompassIcon,
  LightbulbIcon,
  LucideIcon
} from "lucide-react"

import type { Experience } from "@/features/portfolio/types/experiences"
import { experiences } from "@/lib/portfolio-config"

// Map string icon names to actual Lucide components
const IconMap: Record<string, LucideIcon> = {
  CodeXmlIcon,
  LightbulbIcon,
  DraftingCompassIcon,
  BriefcaseBusinessIcon,
}

export const EXPERIENCES: Experience[] = (experiences || []).map((exp) => ({
  ...exp,
  companyIcon: exp.companyIcon ? React.createElement(IconMap[exp.companyIcon] || BriefcaseBusinessIcon) : undefined,
  positions: exp.positions.map((pos) => ({
    ...pos,
    icon: pos.icon ? React.createElement(IconMap[pos.icon] || CodeXmlIcon) : undefined,
  })),
}))
