/**
 * social-links.ts — auto-generated from portfolio.json
 *
 * ✏️  To edit your social links, open: src/config/portfolio.json → "social"
 *    Do NOT edit this file directly.
 */

import type { SocialProfile } from "@/features/portfolio/types/social-links"
import { social } from "@/lib/portfolio-config"

export const SOCIAL = social satisfies Record<string, SocialProfile>

export type SocialName = keyof typeof SOCIAL

export type SocialLink = SocialProfile & { name: SocialName }

export const SOCIAL_LINKS: SocialLink[] = (
  Object.entries(SOCIAL) as [SocialName, SocialProfile][]
).map(([name, profile]) => ({ name, ...profile }))
