/**
 * user.ts — auto-generated from portfolio.json
 *
 * ✏️  To edit your personal info, open: src/config/portfolio.json
 *    Do NOT edit this file directly.
 */

import type { User } from "@/features/portfolio/types/user"
import { personal, flipSentences, jobs, about, emailB64 } from "@/lib/portfolio-config"

export const USER: User = {
  displayName: personal.displayName,
  username: personal.username,
  gender: personal.gender,
  pronouns: personal.pronouns,
  bio: personal.bio,
  flipSentences,
  address: personal.address,
  timeZone: personal.timezone,
  emailB64,
  website: personal.website,
  jobTitle: personal.jobTitle,
  jobs,
  about,
  avatar: personal.avatar,
  ogImage: personal.ogImage,
  keywords: personal.keywords,
  dateCreated: personal.dateCreated,
}