/**
 * site.ts — auto-generated from portfolio.json
 *
 * ✏️  To edit nav links, site URL, or metadata, open: src/config/portfolio.json
 *    Do NOT edit this file directly.
 */

import type { Route } from "next"

import type { NavItem } from "@/types/nav"
import { navigation, personal, site, social } from "@/lib/portfolio-config"

export const SITE_INFO = {
  name: personal.displayName,
  url: process.env.NEXT_PUBLIC_APP_URL || site.url,
  ogImage: personal.ogImage,
  description: personal.bio,
  keywords: personal.keywords,
}

export const LICENSE = {
  name: "MIT License",
  url: "https://github.com/ncdai/chanhdai.com/blob/main/LICENSE",
}

export const META_THEME_COLORS = {
  light: "#ffffff",
  dark: "#09090b",
}

export const MAIN_NAV: NavItem<Route>[] = navigation.map((item) => ({
  title: item.title,
  href: item.href as Route,
}))

export const MOBILE_NAV: NavItem<Route>[] = [
  { title: "Home", href: "/" as Route },
  ...MAIN_NAV,
]

export const X_HANDLE = ""
export const GITHUB_USERNAME = social.github?.handle ?? ""
export const SOURCE_CODE_GITHUB_REPO = site.githubRepo
export const SOURCE_CODE_GITHUB_URL = site.githubUrl

export const SPONSORSHIP_URL = "https://github.com/sponsors/ncdai"

export const UTM_PARAMS = {
  utm_source: site.url,
}
